### ISSUE TITLE
Write cron job script for Ubuntu server

### ISSUE THREAD

**Issue by bulbil** [swat-ds/2018-liblab-projects#11]

**Comment by Mualpha7** [comment]
Once we get certbot-auto and move it to the right location, we can specify the periodicity of the renewal by opening the crontab file with 'sudo crontab -e' and at the last line of the file (after the text found in the file) add the following: '45 2 * * 6 cd /etc/letsencrypt/ && ./certbot-auto renew && /etc/init.d/apache2 restart'.
