### ISSUE TITLE
Specific Steps to Implement SSL

### ISSUE THREAD

**Issue by bulbil** [swat-ds/2018-liblab-projects#9]
- a CentOS distro
- Ubuntu 16 server
- any links to useful walkthroughs or guides

Due 11/26

**Comment by Mualpha7** [comment]
I installed CentOS 7 on my laptop. It works well and without issues. I wasn't sure if I also needed Ubuntu 16 or just one of them, since they are both Linux distros. As for the walkthrough/guide, I found this one that I liked the most: https://www.smashingmagazine.com/2017/06/guide-switching-http-https/

**Comment by bulbil** [comment]
Let's revisit this:

- a text document with resources and specific steps and commands entered to get the ds-sandbox.fun up and running with cert and ssl

Resources we looked at today:

- [certbot](https://certbot.eff.org/lets-encrypt/ubuntuxenial-apache)
- [digital ocean](https://www.digitalocean.com/community/tutorials/how-to-secure-apache-with-let-s-encrypt-on-ubuntu-14-04)
- [smashing magazine](https://www.smashingmagazine.com/2017/06/guide-switching-http-https/)

**Comment by Mualpha7** [comment]
I haven't had the chance to write a formal set of steps in a document, but it's comming! Here is a draft of the steps we took. I'll add more details as we continue working on it today:
---Steps Taken---
-For setup, use PuTTYgen to generate a public and a private .ppk key pair. Save both keys.
-To connect to the server, go on PuTTY and use fveronf1@34.237.205.134 as hostname (or IP address), where fveronf1 is the user name (not the same as the laptop's, which is mualp) and 34.237.205.134 is the IP address of the AWS server to connect to.
-On SSH>Auth, use the private key generated through PuTTYgen (FranciscoPrivatekey.ppk).
-Click "Open" to connect. You will be prompted to enter your user name and password for login, given by:
*Username: fveronf1
*Password: fveronf1 for AWS
		   Mualpha7! for PUTTY session
-Now you are connected to the school's server. Admin privileges and permission to make changes have been granted to you by Nabil. Trickiest part of the process was setting up admin privileges (required some changes from both ends).
-Follow Certbot's instructions and commands on "Certbot" under "Resources used". Specify "I'm using Apache on Ubuntu 16.04 (xenial)". All commands worked and Certbot converted the http website to https with no issues.
---Resources used---
-Digital Ocean: https://www.digitalocean.com/community/tutorials/how-to-install-an-ssl-certificate-from-a-commercial-certificate-authority
-Smashing Magazine: https://www.smashingmagazine.com/2017/06/guide-switching-http-https/
-Certbot: https://certbot.eff.org/lets-encrypt/ubuntuxenial-apache

**Comment by bulbil** [comment]
We'll want to make sure this includes a sample script for implementing the cron job, some kind of shell hook that invokes `certbot renew`.

**Comment by Mualpha7** [comment]
To do this, we need to install certbot-auto (once certbot is already installed).

Get certbot-auto with `wget https://dl.eff.org/certbot-auto && chmod a+x certbot-auto` and then use `sudo mv certbot-auto /etc/letsencrypt/`. To specify the periodicity of the renewal, open the crontab file with `sudo crontab -e` and at the last line of the file (after the text found in the file) add the following: `45 2 * * 6 cd /etc/letsencrypt/ && ./certbot-auto renew && /etc/init.d/apache2 restart`. The numbers at the beginning specify the regularity with which the script will check to see if a renewal is needed. This specific line of code makes sure the certificate gets checked weekly and renewed before the 90 days expiration deadline.

Finally, once this cron job file is modified, we just need to make sure that the permissions are right. Run `chmod 755 certbot-auto`. Additionally, the `certbot-auto` file needs to operate from root. Run `ls -l` to check, and if it's not operating from root, then run `sudo chown root:root certbot-auto`. Now the cron job file should be working fine and updating on a weekly basis.
